const CURSORSTYLES = {
  default: "default",
  auto: "auto",
  crosshair: "crosshair",
  pointer: "pointer",
  move: "move",
  text: "text",
  wait: "wait",
  help: "help",
  progress: "progress",
  notAllowed: "not-allowed",
  noDrop: "no-drop",
  allScroll: "all-scroll",
  colResize: "col-resize",
  rowResize: "row-resize",
  nResize: "n-resize",
  eResize: "e-resize",
  sResize: "s-resize",
  wResize: "w-resize",
  neResize: "ne-resize",
  nwResize: "nw-resize",
  seResize: "se-resize",
  swResize: "sw-resize",
  ewResize: "ew-resize",
  nsResize: "ns-resize",
  neswResize: "nesw-resize",
  nwseResize: "nwse-resize",
  zoomIn: "zoom-in",
  zoomOut: "zoom-out",
  grab: "grab",
  grabbing: "grabbing",
  bottomRightCorner: "nwse-resize",
  bottomLeftCorner: "nesw-resize",
  topRightCorner: "nesw-resize",
  topLeftCorner: "nwse-resize",
};

export default CURSORSTYLES;
